version: '3'

services:

  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    container_name: api
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    restart: always
    depends_on:
      api:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
