version: '3'

services:

  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    container_name: api
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: db
